#ifndef DREAMCAM_GUI_H
#define DREAMCAM_GUI_H

#if defined(DREAMCAMGUI_EXPORT_LIB)
#  define DREAMCAMGUI_EXPORT Q_DECL_EXPORT
#else
#  define DREAMCAMGUI_EXPORT Q_DECL_IMPORT
#endif

#endif // DREAMCAM_GUI_H
