#ifndef DREAMCAM_COM_H
#define DREAMCAM_COM_H

#if defined(DREAMCAMCOM_EXPORT_LIB)
#  define DREAMCAMCOM_EXPORT Q_DECL_EXPORT
#else
#  define DREAMCAMCOM_EXPORT Q_DECL_IMPORT
#endif

#endif // DREAMCAM_COM_H
