#ifndef DREAMCAM_GUI_COMMON_H
#define DREAMCAM_GUI_COMMON_H

#if defined(GPSTUDIO_GUI_EXPORT_LIB)
#  define GPSTUDIO_GUI_EXPORT Q_DECL_EXPORT
#else
#  define GPSTUDIO_GUI_EXPORT Q_DECL_IMPORT
#endif

#endif // DREAMCAM_GUI_COMMON_H
