#ifndef GPSTUDIO_COM_COMMON_H
#define GPSTUDIO_COM_COMMON_H

#if defined(GPSTUDIO_COM_EXPORT_LIB)
#  define GPSTUDIO_COM_EXPORT Q_DECL_EXPORT
#else
#  define GPSTUDIO_COM_EXPORT Q_DECL_IMPORT
#endif

#endif // GPSTUDIO_COM_COMMON_H
